### ISSUE TITLE
Database error: "UNIQUE constraint failed: triples.subject, triples.predicate, triples.object, triples.properties"

### ISSUE THREAD

**Issue by alecStewart1** [ahyatt/triples#4] opened 2023-07-15 04:53 UTC
Hello,

I got this error when upgrading to the newest version of triples and ekg, and then trying to create a new note. 

**triples version:**

0.3.3

**ekg version:**

20230620.1807

**Exact error:**

```
triples-connect: Database error: "UNIQUE constraint failed: triples.subject, triples.predicate, triples.object, triples.properties"
```

**Backtrace:**

```
Debugger entered--Lisp error: (sqlite-error "UNIQUE constraint failed: triples.subject, triples...")
  triples-setup-table-for-builtin(#<sqlite db=0x55dfc14e5450 name=/home/alec/Documents/Org/EKG/ekg.db>)
  triples-connect("/home/alec/Documents/Org/EKG/ekg.db")
  ekg-connect()
  ekg--save-note-in-buffer()
  ekg-capture-finalize()
  funcall-interactively(ekg-capture-finalize)
  command-execute(ekg-capture-finalize)
```

I ran `.recover` in the sqlite repl for the database to see if that would fix things, but alas it didn't.

**Comment by ahyatt** [comment] 2023-07-15 14:40
Thank you for reporting this error!  I'm sorry you ran into it.   Can you let me know if you've been running the built-in sqlite or emacsql previously?  I assume you must be using sqlite now, based on the error.

What has happened is that your database, for reasons I don't know (but I've seen before on both my and other's databases) has either lost your indexes that ensure uniqueness, or never had it.  Without those indexes, you will have duplicate rows, which messes up ekg.   We have a fix for this, but it is run as part of an upgrade, and before we upgrade, we need to connect to the database. The problem is, when we connect, we try to ensure the indexes exist, which they can't until the dups are fixed.  I'm adding logic into the `triples` package to detect something has gone wrong and try the fix (which already exists as part of the upgrade).  I'm going to push a commit on the `develop` branch, please try it and let me know if it fixes your problem.

**Comment by alecStewart1** [comment] 2023-07-16 04:34
No worries! I've been on the development version of Emacs for a few months now, it's been the built-in sqlite module.

Luckily there was only one note on my desktop. The rest are on my work laptop, and there's been no issues there. Just need to setup syncthing to sync between those two devices.

**Comment by ahyatt** [comment] 2023-07-17 04:11
@alecStewart1 thanks, please let me know when you verify the fix.

**Comment by richardmurri** [comment] 2023-07-24 16:51
I'm not the original reporter, but I can verify this worked for me.

**Comment by ahyatt** [comment] 2023-07-25 04:21
Sweet, thanks!  I'll create a new release in the next few days.

**Closed as completed by ahyatt** 2023-07-25 04:21 UTC
